# Data Cleaning

## Import

In [391]:
import pandas as pd
import numpy as np
import re

pd.set_option('display.float_format', '{:.2f}'.format)

raw_df = pd.read_csv('data/movies.csv', on_bad_lines='skip')
df = raw_df.copy()

## Checking out dataset

In [392]:
print(df.isna().sum())

df[30:200].head(20)

MOVIES         0
YEAR         644
GENRE         80
RATING      1820
ONE-LINE       0
STARS          0
VOTES       1820
RunTime     2958
Gross       9539
dtype: int64

,MOVIES,YEAR,GENRE,RATING,ONE-LINE,STARS,VOTES,RunTime,Gross
30,Fear Street: 1666,(2021),"\nHorror, Mystery",6.70,\nThe origins of Sarah Fier's curse are finall...,\n Director:\nLeigh Janiak\n| \n Stars:\...,"27,447",114.00,NaN
31,Animal Kingdom,(2016– ),"\nCrime, Drama",8.20,"\nCenters on a Southern California family, who...","\n \n Stars:\nShawn Hatosy, \nBe...","26,926",60.00,NaN
32,Brooklyn Nine-Nine,(2013–2022),"\nComedy, Crime",8.40,\nComedy series following the exploits of Det....,"\n \n Stars:\nAndy Samberg, \nSt...","248,583",22.00,NaN
33,NCIS: Naval Criminal Investigative Service,(2003– ),"\nAction, Crime, Drama",7.70,\nThe cases of the Naval Criminal Investigativ...,"\n \n Stars:\nMark Harmon, \nDav...","125,619",60.00,NaN
34,Kingdom,(2019– ),"\nAction, Drama, History",8.40,\nWhile strange rumors about their ill King gr...,"\n \n Stars:\nJu Ji-Hoon, \nBae ...","34,906",45.00,NaN
35,Modern Family,(2009–2020),"\nComedy, Drama, Romance",8.40,\nThree different but related families face tr...,"\n \n Stars:\nEd O'Neill, \nSofí...","378,030",22.00,NaN
36,Titans,(I) (2018– ),"\nAction, Adventure, Crime",7.70,\nA team of young superheroes combat evil and ...,"\n \n Stars:\nBrenton Thwaites, ...","73,656",45.00,NaN
37,The Witcher,(2019– ),"\nAction, Adventure, Fantasy",8.20,"\nGeralt of Rivia, a solitary monster hunter, ...","\n \n Stars:\nHenry Cavill, \nAn...","336,484",60.00,NaN
38,Downton Abbey,(2010–2015),"\nDrama, Romance",8.70,\nA chronicle of the lives of the British aris...,"\n \n Stars:\nHugh Bonneville, \...","171,804",58.00,NaN
39,Shingeki no kyojin,(2013–2022),"\nAnimation, Action, Adventure",9.00,\nAfter his hometown is destroyed and his moth...,"\n \n Stars:\nYûki Kaji, \nMarin...","242,582",24.00,NaN
40,Suits,(2011–2019),"\nComedy, Drama",8.40,"\nOn the run from a drug deal gone bad, brilli...","\n \n Stars:\nGabriel Macht, \nP...","374,263",44.00,NaN
41,La casa de papel,(2017–2021),"\nAction, Crime, Mystery",8.30,\nAn unusual group of robbers attempt to carry...,"\n \n Stars:\nÚrsula Corberó, \n...","341,858",70.00,NaN
42,Schitt's Creek,(2015–2020),\nComedy,8.50,\nWhen rich video-store magnate Johnny Rose an...,"\n \n Stars:\nEugene Levy, \nCat...","90,728",22.00,NaN
43,Outlander,(2014– ),"\nDrama, Fantasy, Romance",8.40,\nAn English combat nurse from 1945 is mysteri...,"\n \n Stars:\nCaitriona Balfe, \...","134,991",64.00,NaN
44,The Last Kingdom,(2015– ),"\nAction, Drama, History",8.40,\nAs Alfred the Great defends his kingdom from...,"\n \n Stars:\nAlexander Dreymon,...","94,650",60.00,NaN
45,Black Mirror,(2011– ),"\nDrama, Sci-Fi, Thriller",8.80,"\nAn anthology series exploring a twisted, hig...","\n \n Stars:\nDaniel Lapaine, \n...","469,407",60.00,NaN
46,Ozark,(2017– ),"\nCrime, Drama, Thriller",8.40,\nA financial advisor drags his family from Ch...,"\n \n Stars:\nJason Bateman, \nL...","206,090",60.00,NaN
47,The Crown,(2016– ),"\nBiography, Drama, History",8.60,\nFollows the political rivalries and romance ...,"\n \n Stars:\nClaire Foy, \nOliv...","169,517",58.00,NaN
48,Sweet Tooth,(2021– ),"\nAction, Adventure, Drama",7.90,\nA boy who is half human and half deer surviv...,"\n \n Stars:\nNonso Anozie, \nCh...","37,142",NaN,NaN
49,Army of the Dead,(2021),"\nAction, Crime, Horror",5.80,"\nFollowing a zombie outbreak in Las Vegas, a ...",\n Director:\nZack Snyder\n| \n Stars:\n...,"132,378",148.00,NaN

## Processing

In [393]:
df = df.drop_duplicates()
df = df.rename(columns = str.title)
df = df.rename(columns = {'One-Line' : 'One_Line_Summary'})

## Movies
df['Movies'] = df['Movies'].str.strip()

## Year
df['Year'] = df['Year'].str.strip()
df['Year'] = df['Year'].str.replace(r'[()]', '' ,regex = True)
df['Year'] = df['Year'].str.replace(r'[–—]', '-', regex=True)


df[['Start_Year', 'End_Year']] = df['Year'].str.extract(r'(\d{4})-?(\d{4})?')
df[['Start_Year', 'End_Year']] = df[['Start_Year', 'End_Year']].fillna('Unknown')


df['Season'] = df['Year'].str.extract(r'([I|X|V|L]+)')
df['Season'] = df['Season'].str.strip().fillna('Unknown')


## Genre
df[['Genre1', 'Genre2', 'Genre3']] = df['Genre'].str.strip().str.split(',', expand = True)
df[['Genre1', 'Genre2', 'Genre3']] = df[['Genre1', 'Genre2', 'Genre3']].fillna('None')

##Rating
df['Rating'] = df['Rating'].fillna(0.0)

## Votes
df['Votes'] = pd.to_numeric(df['Votes'], errors = 'coerce')
df['Votes'] = df['Votes'].fillna(0.0)

## Stars
df['Stars'] = df['Stars'].str.replace(r'\n','' ,regex= True)

df['Directors'] = df['Stars'].str.extract(r'Director:\s*([^|]+)').fillna('Unknown')

df['Stars'] = df['Stars'].str.extract(r'Stars:\s*(.+)').fillna('Unknown')

df[['Star_1', 'Star_2', 'Star_3', 'Star_4']] = df['Stars'].str.split(',', n = 3, expand = True)
df[['Star_1', 'Star_2', 'Star_3', 'Star_4']] = df[['Star_1', 'Star_2', 'Star_3', 'Star_4']].apply(lambda col: col.str.strip()).fillna('None')

## One Line Summary
df['One_Line_Summary'] = df['One_Line_Summary'].str.strip()
df['One_Line_Summary'] = df['One_Line_Summary'].str.replace(r'(\n)', '')
df['One_Line_Summary'] = df['One_Line_Summary'].str.replace(r'(Add a Plot)', 'Unknown')

## Gross
df['Gross'] = df['Gross'].str.replace(',', '', regex=False)
df['Gross(Million Dollars)'] = df['Gross'].str.extract(r'(\d+(?:\.\d+)?)').astype(float).round(2).fillna(0.0)

df = df.drop(columns=['Genre', 'Year', 'Stars', 'Gross'])

## Runtime
df['Runtime'] = df['Runtime'].fillna(0.0)

In [394]:
df.head(50)

,Movies,Rating,One_Line_Summary,Votes,Runtime,Start_Year,End_Year,Season,Genre1,Genre2,Genre3,Directors,Star_1,Star_2,Star_3,Star_4,Gross(Million Dollars)
0,Blood Red Sky,6.10,A woman with a mysterious illness is forced in...,0.00,121.00,2021,Unknown,Unknown,Action,Horror,Thriller,Peter Thorwarth,Peri Baumeister,Carl Anton Koch,Alexander Scheer,Kais Setti,0.00
1,Masters of the Universe: Revelation,5.00,The war for Eternia begins again in what may b...,0.00,25.00,2021,Unknown,Unknown,Animation,Action,Adventure,Unknown,Chris Wood,Sarah Michelle Gellar,Lena Headey,Mark Hamill,0.00
2,The Walking Dead,8.20,Sheriff Deputy Rick Grimes wakes up from a com...,0.00,44.00,2010,2022,Unknown,Drama,Horror,Thriller,Unknown,Andrew Lincoln,Norman Reedus,Melissa McBride,Lauren Cohan,0.00
3,Rick and Morty,9.20,An animated series that follows the exploits o...,0.00,23.00,2013,Unknown,Unknown,Animation,Adventure,Comedy,Unknown,Justin Roiland,Chris Parnell,Spencer Grammer,Sarah Chalke,0.00
4,Army of Thieves,0.00,"A prequel, set before the events of Army of th...",0.00,0.00,2021,Unknown,Unknown,Action,Crime,Horror,Matthias Schweighöfer,Matthias Schweighöfer,Nathalie Emmanuel,Ruby O. Fee,Stuart Martin,0.00
5,Outer Banks,7.60,A group of teenagers from the wrong side of th...,0.00,50.00,2020,Unknown,Unknown,Action,Crime,Drama,Unknown,Chase Stokes,Madelyn Cline,Madison Bailey,Jonathan Daviss,0.00
6,The Last Letter from Your Lover,6.80,A pair of interwoven stories set in the past a...,0.00,110.00,2021,Unknown,Unknown,Drama,Romance,None,Augustine Frizzell,Shailene Woodley,Joe Alwyn,Wendy Nottingham,Felicity Jones,0.00
7,Dexter,8.60,"By day, mild-mannered Dexter is a blood-spatte...",0.00,53.00,2006,2013,Unknown,Crime,Drama,Mystery,Unknown,Michael C. Hall,Jennifer Carpenter,David Zayas,James Remar,0.00
8,Never Have I Ever,7.90,The complicated life of a modern-day first gen...,0.00,30.00,2020,Unknown,Unknown,Comedy,None,None,Unknown,Maitreyi Ramakrishnan,Poorna Jagannathan,Darren Barnet,John McEnroe,0.00
9,Virgin River,7.40,"Seeking a fresh start, nurse practitioner Meli...",0.00,44.00,2019,Unknown,Unknown,Drama,Romance,None,Unknown,Alexandra Breckenridge,Martin Henderson,Colin Lawrence,Tim Matheson,0.00
10,Gunpowder Milkshake,6.00,Three generations of women fight back against ...,0.00,114.00,2021,Unknown,Unknown,Action,Adventure,Thriller,Navot Papushado,Karen Gillan,Lena Headey,Carla Gugino,Michelle Yeoh,0.00
11,Lucifer,8.10,Lucifer Morningstar has decided he's had enoug...,0.00,42.00,2016,2021,Unknown,Crime,Drama,Fantasy,Unknown,Tom Ellis,Lesley-Ann Brandt,Lauren German,D.B. Woodside,0.00
12,Fear Street: 1994,6.20,A circle of teenage friends accidentally encou...,0.00,107.00,2021,Unknown,Unknown,Drama,Horror,Mystery,Leigh Janiak,Kiana Madeira,Olivia Scott Welch,Benjamin Flores Jr.,Julia Rehwald,0.00
13,Sex/Life,5.40,A suburban mother of two takes a fantasy-charg...,0.00,0.00,2021,Unknown,Unknown,Comedy,Drama,Romance,Unknown,Sarah Shahi,Mike Vogel,Adam Demos,Margaret Odette,0.00
14,American Horror Story,8.00,An anthology series centering on different cha...,0.00,60.00,2011,Unknown,Unknown,Drama,Horror,Thriller,Unknown,Lady Gaga,Kathy Bates,Angela Bassett,Sarah Paulson,0.00
15,Grey's Anatomy,7.50,A drama centered on the personal and professio...,0.00,41.00,2005,Unknown,Unknown,Drama,Romance,None,Unknown,Ellen Pompeo,Chandra Wilson,James Pickens Jr.,Justin Chambers,0.00
16,Breaking Bad,9.40,A high school chemistry teacher diagnosed with...,0.00,49.00,2008,2013,Unknown,Crime,Drama,Thriller,Unknown,Bryan Cranston,Aaron Paul,Anna Gunn,Betsy Brandt,0.00
17,The Good Doctor,8.10,"Shaun Murphy, a young surgeon with autism and ...",0.00,41.00,2017,Unknown,Unknown,Drama,None,None,Unknown,Freddie Highmore,Hill Harper,Richard Schiff,Antonia Thomas,0.00
18,Atypical,8.30,"Sam, an 18-year-old on the autism spectrum, de...",0.00,30.00,2017,2021,Unknown,Comedy,Drama,None,Unknown,Jennifer Jason Leigh,Keir Gilchrist,Brigette Lundy-Paine,Michael Rapaport,0.00
19,Stranger Things,8.70,"When a young boy disappears, his mother, a pol...",0.00,51.00,2016,Unknown,Unknown,Drama,Fantasy,Horror,Unknown,Millie Bobby Brown,Finn Wolfhard,Winona Ryder,David Harbour,0.00
20,Fear Street: 1978,6.80,"Shadyside, 1978. School's out for summer and t...",0.00,109.00,2021,Unknown,Unknown,Drama,Horror,Mystery,Leigh Janiak,Sadie Sink,Emily Rudd,Ryan Simpkins,McCabe Slye,0.00
21,Friends,8.90,Follows the personal and professional lives of...,0.00,22.00,1994,2004,Unknown,Comedy,Romance,None,Unknown,Jennifer Aniston,Courteney Cox,Lisa Kudrow,Matt LeBlanc,0.00
22,The Flash,7.60,"After being struck by lightning, Barry Allen w...",0.00,43.00,2014,Unknown,Unknown,Action,Adventure,Drama,Unknown,Grant Gustin,Candice Patton,Danielle Panabaker,Carlos Valdes,0.00
23,Peaky Blinders,8.80,"A gangster family epic set in 1900s England, c...",0.00,60.00,2013,Unknown,Unknown,Crime,Drama,None,Unknown,Cillian Murphy,Paul Anderson,Helen McCrory,Sophie Rundle,0.00
24,He-Man and the Masters of the Universe,0.00,Eternia's Prince Adam discovers the power of G...,0.00,0.00,2021,Unknown,Unknown,Animation,Action,Adventure,Unknown,Unknown,None,None,None,0.00
25,Chernobyl,5.00,A story about a heroic fireman who worked as o...,0.00,136.00,2021,Unknown,Unknown,Drama,History,Romance,Danila Kozlovskiy,Danila Kozlovskiy,Oksana Akinshina,Filipp Avdeev,Ravshana Kurkova,0.00
26,Vikings,8.50,Vikings transports us to the brutal and myster...,0.00,44.00,2013,2020,Unknown,Action,Adventure,Drama,Unknown,Katheryn Winnick,Gustaf Skarsgård,Alexander Ludwig,Georgia Hirst,0.00
27,Better Call Saul,8.80,The trials and tribulations of criminal lawyer...,0.00,46.00,2015,Unknown,Unknown,Crime,Drama,None,Unknown,Bob Odenkirk,Rhea Seehorn,Jonathan Banks,Patrick Fabian,0.00
28,Supernatural,8.40,Two brothers follow their father's footsteps a...,0.00,44.00,2005,2020,Unknown,Drama,Fantasy,Horror,Unknown,Jared Padalecki,Jensen Ackles,Jim Beaver,Misha Collins,0.00
29,The Blacklist,8.00,"A new FBI profiler, Elizabeth Keen, has her en...",0.00,43.00,2013,Unknown,Unknown,Crime,Drama,Mystery,Unknown,James Spader,Megan Boone,Diego Klattenhoff,Ryan Eggold,0.00
30,Fear Street: 1666,6.70,The origins of Sarah Fier's curse are finally ...,0.00,114.00,2021,Unknown,Unknown,Horror,Mystery,None,Leigh Janiak,Kiana Madeira,Ashley Zukerman,Gillian Jacobs,Olivia Scott Welch,0.00
31,Animal Kingdom,8.20,"Centers on a Southern California family, whose...",0.00,60.00,2016,Unknown,Unknown,Crime,Drama,None,Unknown,Shawn Hatosy,Ben Robson,Jake Weary,Finn Cole,0.00
32,Brooklyn Nine-Nine,8.40,Comedy series following the exploits of Det. J...,0.00,22.00,2013,2022,Unknown,Comedy,Crime,None,Unknown,Andy Samberg,Stephanie Beatriz,Terry Crews,Melissa Fumero,0.00
33,NCIS: Naval Criminal Investigative Service,7.70,The cases of the Naval Criminal Investigative ...,0.00,60.00,2003,Unknown,Unknown,Action,Crime,Drama,Unknown,Mark Harmon,David McCallum,Sean Murray,Pauley Perrette,0.00
34,Kingdom,8.40,While strange rumors about their ill King grip...,0.00,45.00,2019,Unknown,Unknown,Action,Drama,History,Unknown,Ju Ji-Hoon,Bae Doona,Kim Sungkyu,Hye-jun Kim,0.00
35,Modern Family,8.40,Three different but related families face tria...,0.00,22.00,2009,2020,Unknown,Comedy,Drama,Romance,Unknown,Ed O'Neill,Sofía Vergara,Julie Bowen,Ty Burrell,0.00
36,Titans,7.70,A team of young superheroes combat evil and ot...,0.00,45.00,2018,Unknown,I,Action,Adventure,Crime,Unknown,Brenton Thwaites,Teagan Croft,Anna Diop,Ryan Potter,0.00
37,The Witcher,8.20,"Geralt of Rivia, a solitary monster hunter, st...",0.00,60.00,2019,Unknown,Unknown,Action,Adventure,Fantasy,Unknown,Henry Cavill,Anna Shaffer,Freya Allan,Adjoa Andoh,0.00
38,Downton Abbey,8.70,A chronicle of the lives of the British aristo...,0.00,58.00,2010,2015,Unknown,Drama,Romance,None,Unknown,Hugh Bonneville,Phyllis Logan,Elizabeth McGovern,Brendan Coyle,0.00
39,Shingeki no kyojin,9.00,After his hometown is destroyed and his mother...,0.00,24.00,2013,2022,Unknown,Animation,Action,Adventure,Unknown,Yûki Kaji,Marina Inoue,Josh Grelle,Yui Ishikawa,0.00
40,Suits,8.40,"On the run from a drug deal gone bad, brillian...",0.00,44.00,2011,2019,Unknown,Comedy,Drama,None,Unknown,Gabriel Macht,Patrick J. Adams,Meghan Markle,Sarah Rafferty,0.00
41,La casa de papel,8.30,An unusual group of robbers attempt to carry o...,0.00,70.00,2017,2021,Unknown,Action,Crime,Mystery,Unknown,Úrsula Corberó,Álvaro Morte,Itziar Ituño,Pedro Alonso,0.00
42,Schitt's Creek,8.50,When rich video-store magnate Johnny Rose and ...,0.00,22.00,2015,2020,Unknown,Comedy,None,None,Unknown,Eugene Levy,Catherine O'Hara,Dan Levy,Annie Murphy,0.00
43,Outlander,8.40,An English combat nurse from 1945 is mysteriou...,0.00,64.00,2014,Unknown,Unknown,Drama,Fantasy,Romance,Unknown,Caitriona Balfe,Sam Heughan,Duncan Lacroix,Sophie Skelton,0.00
44,The Last Kingdom,8.40,As Alfred the Great defends his kingdom from N...,0.00,60.00,2015,Unknown,Unknown,Action,Drama,History,Unknown,Alexander Dreymon,Eliza Butterworth,Arnas Fedaravicius,Millie Brady,0.00
45,Black Mirror,8.80,"An anthology series exploring a twisted, high-...",0.00,60.00,2011,Unknown,Unknown,Drama,Sci-Fi,Thriller,Unknown,Daniel Lapaine,Hannah John-Kamen,Michaela Coel,Beatrice Robertson-Jones,0.00
46,Ozark,8.40,A financial advisor drags his family from Chic...,0.00,60.00,2017,Unknown,Unknown,Crime,Drama,Thriller,Unknown,Jason Bateman,Laura Linney,Sofia Hublitz,Skylar Gaertner,0.00
47,The Crown,8.60,Follows the political rivalries and romance of...,0.00,58.00,2016,Unknown,Unknown,Biography,Drama,History,Unknown,Claire Foy,Olivia Colman,Imelda Staunton,Matt Smith,0.00
48,Sweet Tooth,7.90,A boy who is half human and half deer survives...,0.00,0.00,2021,Unknown,Unknown,Action,Adventure,Drama,Unknown,Nonso Anozie,Christian Convery,Adeel Akhtar,Stefania LaVie Owen,0.00
49,Army of the Dead,5.80,"Following a zombie outbreak in Las Vegas, a gr...",0.00,148.00,2021,Unknown,Unknown,Action,Crime,Horror,Zack Snyder,Dave Bautista,Ella Purnell,Ana de la Reguera,Omari Hardwick,0.00